---
apiVersion: v1
kind: Namespace
metadata:
   name: {{ .Values.namespace.name }}

# ---
# apiVersion: v1
# kind: Service
# metadata:
  # name: simple-go
# spec:
  # selector:
    # app: simple-go
  # ports:
    # - port: 80
      # targetPort: 8080
  # type: LoadBalancer


